apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankapp-ingress
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:375916767526:certificate/e19eb9cf-0700-425c-81f0-53262641730c
    # âœ… ENABLE STICKY SESSIONS (THIS IS THE KEY)
    alb.ingress.kubernetes.io/target-group-attributes: >
      stickiness.enabled=true,
      stickiness.lb_cookie.duration_seconds=172800
spec:
  rules:
    - host: dev.pashtun-verse.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bankapp-service
                port:
                  number: 80
