apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankapp-ingress
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:602643042585:certificate/b6ee2c32-3cf0-4e56-999b-a50188e79d5f
    alb.ingress.kubernetes.io/target-group-attributes: >
      stickiness.enabled=true,
      stickiness.lb_cookie.duration_seconds=172000
spec:
  rules:
    - host: dev.pashtun-verse.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bankapp-service
                port:
                  number: 80
